const About = () => {
    return (
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in iaculis tortor. Etiam id quam ultrices, aliquet ipsum a, ultrices purus. Aliquam id mauris non tortor tristique varius. Vestibulum sed gravida magna. Sed suscipit leo tortor, vel accumsan nunc aliquet ut. Nullam in ipsum pellentesque sapien mattis rhoncus eget et ex. Praesent id placerat odio. Integer eget dapibus turpis. Integer ultricies, dui scelerisque molestie molestie, lacus mi cursus tortor, sed vulputate augue purus in felis. Aliquam urna metus, tempor a lectus a, vestibulum semper diam. Nullam maximus massa sit amet sapien vehicula, ut finibus elit molestie. Morbi mollis ultricies nisi id congue. Nunc quis nulla vestibulum, lobortis odio et, imperdiet nisl. Etiam interdum purus quis justo faucibus feugiat.
            Aenean rutrum venenatis tempor. Maecenas eget aliquet sem. Praesent lacinia non nunc auctor hendrerit. Cras maximus velit vel turpis vehicula, in vestibulum elit rhoncus. Aenean commodo, elit ut iaculis euismod, risus sem ullamcorper massa, vitae dapibus justo massa nec nulla. Ut tortor dui, convallis ut orci at, sodales bibendum arcu. Etiam eu tellus vulputate, feugiat lacus et, euismod libero. Maecenas tempus nisi fringilla ligula varius eleifend. Praesent blandit velit vitae consectetur gravida. Suspendisse fermentum nec leo at hendrerit. Duis fermentum lacus neque, vel mattis est ultricies at. Vestibulum eu eros aliquam, posuere est vel, interdum turpis.
            Curabitur luctus vel lectus a semper. Curabitur blandit finibus lectus. Maecenas vel lectus et dui finibus aliquet eget sit amet ipsum. In porttitor ex sit amet neque rhoncus, eget viverra tortor pellentesque. Vestibulum condimentum nulla ac nunc venenatis, eu gravida massa interdum. Duis ultrices, tortor eu rutrum tristique, quam turpis convallis justo, ut tristique quam arcu sed nisi. Curabitur volutpat mi ac tortor consectetur, vel suscipit dui consectetur. Integer nisi ipsum, semper in lacus eu, pulvinar porttitor elit. Donec faucibus velit libero, et semper quam laoreet quis. Nullam aliquam consectetur ante a congue.
            In efficitur neque id imperdiet convallis. Vestibulum vel turpis ex. Sed eget posuere urna. Suspendisse potenti. Phasellus dignissim, tortor sed aliquet vestibulum, urna justo commodo ligula, sit amet lacinia magna libero sit amet nunc. Donec quis lectus quam. Vestibulum non tortor ipsum. Proin gravida, libero et tempus tristique, ex sapien imperdiet arcu, id hendrerit ex ipsum quis elit. Donec faucibus leo nibh, id egestas tellus porttitor et. Maecenas molestie mattis tellus, quis sollicitudin metus sodales ut. Donec luctus ac quam et consequat.
            Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas non risus vel nisl auctor accumsan at nec libero. Proin in cursus arcu. Curabitur rhoncus, tellus eu viverra fermentum, nisi turpis vestibulum diam, non condimentum purus nunc ac velit. Aenean dapibus posuere enim eget auctor. Phasellus et dignissim lectus, in fringilla metus. Fusce scelerisque dignissim varius. 
        </p>
    )
}

export default About